### ISSUE TITLE
Is there any schedule about 7-zip?

### ISSUE THREAD

**Issue by victorwoo** [ivoronin/ArchiveMounter#2]
Hi friends, is there any schedule about 7-zip support?
Because .zip doesn't support long path and has a low compress rate. RAR is some kind of commercial. 7-zip is a good choice (open source, cross platform).

**Comment by victorwoo** [comment]
I can't develop MacOS applications, but I did some research and hope these links helps:

https://github.com/kedazo/fuse-7z-ng
https://github.com/exmakhina/fuse-7z
https://www.openhub.net/p/fuse-7z

**Comment by ivoronin** [comment]
I'll look into it

**Comment by ivoronin** [comment]
Unfortunately this components aren't mature enough and can't be built on macOS without heavy modification, therefore ArchiveMounter cannot provide support for 7z archives for now.

**Comment by victorwoo** [comment]
Thanks anyway!
