### ISSUE TITLE
macOS 10.10 compatibility issues (was: Corrupted DMG on MAC OSX 10.10)

### ISSUE THREAD

**Issue by wanglongqi** [ivoronin/ArchiveMounter#3]
I downloaded three versions of the released dmg. All return the same error message. Is my Mac OS version too old and not supported?

> MD5 (Archive.Mounter.1.3.0.dmg) = b15f7ec426b7ff9751e00112db8b0436
> MD5 (Archive.Mounter.1.3.1.dmg) = 2c1044d32b20812a93b3fe2768494b92
> MD5 (Archive.Mounter.1.4.0.dmg) = 12f453b5aef4a5b66f2b7d2f4d49635e
> 

![image](https://user-images.githubusercontent.com/6874783/50737319-a6d93c80-1202-11e9-8a95-d59a2ad554ee.png)

**Comment by ivoronin** [comment]
Checksums are all good.
Release disk images are compressed using lzfse algorithm introduced in 10.11.
Please check the attached zip.
[Archive.Mounter.1.4.0.zip](https://github.com/ivoronin/ArchiveMounter/files/2730744/Archive.Mounter.1.4.0.zip)
Let me know if software is working on 10.10.

**Comment by wanglongqi** [comment]
Thanks for the promptly reply. I am afraid the answer is no. The bundle fuse-zip is built for 10.13. I can compile fuse-zip under 10.10. So I think it is possible to make a release for 10.10.

> Dyld Error Message:
>   Symbol not found: _syslog$DARWIN_EXTSN
>   Referenced from: Archive Mounter.app/Contents/Executables/fuse-zip (which was built for Mac OS X 10.13)
>   Expected in: /usr/lib/libSystem.B.dylib
>

**Comment by ivoronin** [comment]
Try this build please.
[Archive.Mounter.1.4.1rc1.zip](https://github.com/ivoronin/ArchiveMounter/files/2736721/Archive.Mounter.1.4.1rc1.zip)

**Comment by wanglongqi** [comment]
Great job, @ivoronin. It works on 10.10 now. Thanks! Since fuse-zip doesn't support zip file with password, it is understandable Archive Mounter also cannot support zip file with password.

**Comment by ivoronin** [comment]
Fixed in v1.4.2

**Comment by ivoronin** [comment]
@wanglongqi can you please run `/Applications/Archive\ Mounter.app/Contents/Executables/rar2fs` (with no arguments)?
I suspect there is another issue present.

**Comment by wanglongqi** [comment]
@ivoronin looks no problem.
> Usage: rar2fs source mountpoint [options]
> Try `rar2fs -h' or `rar2fs --help' for more information.
